### ISSUE TITLE
Typescript Workflow hinzufügen

### ISSUE THREAD

**Issue by TheDevGuyMarc** [Johannes-Schiel/ud-basic-webdev-setup#15]
Es wäre schön einen Typescript Workflow im gulpfile zu haben. Das heißt: Compile, Minify, Testing und eventuell noch weitere Schritte wenn dir was einfällt :) Ich brauche diese Funktionalität für Typescript+ Express API Development

**Comment by Johannes-Schiel** [comment]
Wer ich mit in eine Zukünftige Version machen aber denke wird noch etwas dauern.

**Comment by Tracer1337** [comment]
Ist dieses Issue noch aktuell? Ich habe Zeit (und Lust lol) es umzusetzen

**Comment by Johannes-Schiel** [comment]
kannst du gerne machen :D hab wenig zeit grade
