### ISSUE TITLE
Schnellere Javascript Builds mit esbuild

### ISSUE THREAD

**Issue by Tracer1337** [Johannes-Schiel/ud-basic-webdev-setup#27]
## Vorschlag

Verwendung von [esbuild](https://esbuild.github.io/) anstelle von Browserify als Javascript Bundler. Dadurch wird die Kompilierzeit auf ein Minimum reduziert. In [einem meiner Projekte](https://github.com/wolfgang-bot/frontend/tree/master/packages/static) verwende ich THREE.js, wodurch die Kompilierzeit mit Browserify bei ~200ms liegt, mit esbuild sind es <10ms (>95% Reduzierung).

## Umsetzung

Eine mögliche Umsetzung ist [hier](https://github.com/wolfgang-bot/frontend/blob/master/packages/static/gulpfile.js) zu finden.

**Comment by Johannes-Schiel** [comment]
Find ich gut hab ich eingebaut.
