### ISSUE TITLE
Template Engine (EJS) für repetetives HTML

### ISSUE THREAD

**Issue by Tracer1337** [Johannes-Schiel/ud-basic-webdev-setup#28]
## Vorschlag

Verwendung von [EJS](https://ejs.co/), um Komponenten und ganze Layouts wiederverwenden zu können. Der Quellcode einer Seite kann vor der Kompilierung so aussehen:

> src/contact.ejs
```ejs
<!DOCTYPE html>
<html lang="en">

<%- include("partials/head", { title: "Contact" }) %>

<body>
    <div class="container">
        <%- include("partials/header") %>

        <section id="contact">
            <h4>Contact</h4>
        </section>
    </div>

    <%- include("partials/footer") %>

    <%- include("partials/scripts") %>
</body>

</html>
```

In dem Beispiel gibt es einen Ordner ``src/partials``, in dem die Komponenten liegen. Eine Komponente kann so aussehen:

> src/partials/head.ejs
```ejs
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/main.min.css">
    <link rel="icon" href="/assets/favicon.ico" />
    <meta name="theme-color" content="#000000" />
    <title>Meine Webseite | <%- title %></title>
</head>
```

Das vollständige Beispiel ist in [diesem Repository](https://github.com/wolfgang-bot/frontend/tree/master/packages/static/src) zu finden.

> Note: Komponenten können auch Parameter entgegennehmen. Siehe im Beispiel ``<%- title %>``

> Note: Der EJS Compiler akzeptiert Javascript Variablen als Parameter, auf die in den Templates zugegriffen werden kann.

## Umsetzung

Eine mögliche Umsetzung ist [hier](https://github.com/wolfgang-bot/frontend/blob/master/packages/static/gulpfile.js) zu finden.

**Comment by Johannes-Schiel** [comment]
Klingt nach einem guten Tool, jedoch wird es erstmal nicht hier eingebaut werden. Da es hier relativ "Minimal" zugeht und sowas jemand der grade startet noch mehr verwirrt als das Setup es eh schon macht :D
