### ISSUE TITLE
Umgebungsvariablen an Templates übergeben (zu #28)

### ISSUE THREAD

**Issue by Tracer1337** [Johannes-Schiel/ud-basic-webdev-setup#29]
Dieses Issue setzt die Implementierung von #28 voraus.

## Vorschlag

Zugriff auf Umgebungsvariablen in den Templates. Am besten erklärt an einem praktischen Beispiel:

```
<a href="https://discord.com/...<%= process.env.DISCORD_BOT_CLIENT_ID  %>">Invite</a>
```

Hier wird die Client-ID eines Discord Bots aus den Umgebungsvariablen genommen und daraus ein Einladungslink generiert.

## Umsetzung

Eine mögliche Umsetzung ist [hier](https://github.com/wolfgang-bot/frontend/blob/master/packages/static/gulpfile.js) zu finden.

**Comment by Johannes-Schiel** [comment]
Hier das gleiche wird "erstmal" nicht kommen denke ich.
