### ISSUE TITLE
Sourcemaps nicht im Production Build erstellen

### ISSUE THREAD

**Issue by Tracer1337** [Johannes-Schiel/ud-basic-webdev-setup#30]
## Vorschlag

Sourcemaps für Javascript werden nicht im Production Build erstellt. Damit ist der Quellcode für den Endnutzer nicht (schwerer) einsehbar.

## Umsetzung

Eine mögliche Umsetzung ist [hier](https://github.com/wolfgang-bot/frontend/blob/master/packages/static/gulpfile.js) zu finden.

**Comment by Johannes-Schiel** [comment]
Ist durch den Wechsel auf esbuild jetzt gelöst.

**Comment by Tracer1337** [comment]
Ich glaube, du hast mein Issue falsch verstanden 😂. Der Vorschlag ist, dass die Sourcemaps nicht generiert werden (deshalb steht "Vorschlag" drüber lol). Jetzt grade werden sie nämlich generiert und das stört mich.
