### ISSUE TITLE
Browsersync wird nicht beendet

### ISSUE THREAD

**Issue by Tracer1337** [Johannes-Schiel/ud-basic-webdev-setup#31]
## Problem

Wenn ich die Entwicklungsumgebung ``npm run dev`` über strg + c schließe, wird der Browsersync Server nicht beendet. Die Umgebung kann nicht wieder gestartet werden, weil der Port belegt ist. Erst wenn der Prozess über den Taskmanager geschlossen wird, ist der Port wieder frei.

## Umgebung

Windows 10
node@14.16.1
npm@7.10.0

**Comment by Johannes-Schiel** [comment]
Also bei mir schließt es wenn ich per strg + c die Node Instance beende kann es danach auch einfach neu starten

**Comment by Tracer1337** [comment]
Ich bekomme das grade auch nicht reproduziert. Wenn der Fehler wieder auftritt, öffne ich das Issue wieder.
