### ISSUE TITLE
npm - fibers nicht mehr kompatibel mit Node.js Version >16

### ISSUE THREAD

**Issue by besserdesign** [Johannes-Schiel/ud-basic-webdev-setup#39]
### Was passiert genau?

Siehe: https://www.npmjs.com/package/fibers

`Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit [dacc2fee0f](https://github.com/v8/v8/commit/dacc2fee0f815823782a7e432c79c2a7767a4765) is a breaking change and workarounds are non-trivial.`

### Reproduktion (Schritte)

1.
2.
3.
...

### Mit welchen Feature hast du Probleme?

- [ ] CSS/SASS
- [ ] JavaScript
- [ ] Testing (Jest)
- [ ] TypeScript
- [ ] live Reload
- [ ] Asset export

### Demo link

/

**Comment by Johannes-Schiel** [comment]
Sollte alles kein Problem mehr sein :)
